# Generated by Django 2.2.3 on 2019-12-23 18:21

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='flashcard',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
