# Generated by Django 2.2.3 on 2020-01-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_auto_20200102_0534'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='flashcard',
            managers=[
            ],
        ),
    ]
