# Generated by Django 2.2.3 on 2019-07-16 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('difficulty', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question', models.CharField(max_length=280, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.Category')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.Difficulty')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trivia.Question')),
                ('correct_answer', models.CharField(max_length=64)),
                ('incorrect_b', models.CharField(max_length=64)),
                ('incorrect_c', models.CharField(max_length=64)),
                ('incorrect_d', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TrueFalse',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trivia.Question')),
                ('correct_answer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.DateTimeField(auto_now_add=True)),
                ('datetime_end', models.DateTimeField(blank=True, null=True)),
                ('questions_correct', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.Difficulty')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
