# Generated by Django 2.2.3 on 2019-07-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_auto_20190722_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2),
        ),
    ]
