# Generated by Django 2.2.3 on 2019-07-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_auto_20190717_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='questions_correct',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='total_questions',
            field=models.IntegerField(blank=True),
        ),
    ]
