# Generated by Django 2.2.3 on 2019-07-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0003_auto_20190717_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='questions_correct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='total_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
