# Generated by Django 2.2.3 on 2019-07-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0004_auto_20190717_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=140, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='correct_answer',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='incorrect_b',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='incorrect_c',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='incorrect_d',
            field=models.CharField(max_length=140),
        ),
    ]
